# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cafeinacode
email: edgar@cafeinacode.com
description: > # this means to ignore newlines until "baseurl:"
  A blog mainly about programming because <sarcasm>there's clearly a
  severe lack of them.</sarcasm>
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aleandros.github.io" # the base hostname & protocol for your site
twitter_username: aleandros
github_username:  aleandros

# Build settings
markdown: kramdown
